= BANCS
:toc: manual

== What's this?

This is sample program for simulate Core Bank System.

----
 *  _______
 * |       |
 * |  ESB  | 
 * |       |
 *  -------  
 *     | request
 *     |
 *     |
 *  -------  request          _______
 * |       |-----------------|       |
 * | BANCS |                 |  CARD |
 * |       |-----------------|       |
 *  -------        response   -------
----

1. BANCS listen on 9805, 8805, CARD listen on 8806, BANCS connect to CARD via 8806(mark as connection 1), CARD connect to BANCS via 8805(mark as connection 2)
2. A client simulate ESB send the request message to BANCS via 9902 which listened by BANCS
3. BANCS forward request message to CARD
4. CARD send response message to BANCS

DESIGN PRINCIPLES:

1. Client ESB load the ISO8583 Message from '/etc/bancs.data', which the file keep bunch of Messages, one message per linem, and send to Bancs via 1 connection.
 
2. All Handler contains a listened entrypoint, and started as a separate threads  
    
      Sub threads use pipe to write the message received from socket, main thread read message from pipe, and send the message via write sock fd.
      3 Handler are 3 separate threads, 2 Init be invoked by main thread. The BANCS has 2 Handler and 1 Init; the CARD has 1 Handler and 1 Init.

      Inbound sequence(N/S from ESB, E/W from BANCS to CARD):

          ESB  -  BANCS's InboundHandler  -  BANCS's BancsToCardInit  -  CARD's CardFromBancsHandler   

      Outbound sequence(E/W from CARD to BANCS):

          CARD's CardToBancsInit  -  BANCS's BancsFromCardHandler    

 3. ISO8583 compatible, a tools used for generate ISO message

== Install

[source, bash]
.*Install on x86*
----
rpm -ivh ttcp-1.13-2.x86_64.rpm
----

[source, bash]
.*List installed files*
----
~]# rpm -ql ttcp
/etc/bancs.data
/etc/ttcp.conf
/usr/bin/bancs
/usr/bin/chat
/usr/bin/echoS
/usr/bin/ttcp
----

== Run

=== BANCS and CARD on same host

//TODO

=== BANCS and CARD on different host

There are 2 x86 servers on for BANCS, another for CARD, use default ports pair(8805/8806). 

[source, bash]
.*1. Start CARD*
----
bancs -c 10.1.20.203
----

[source, bash]
.*2. Start BANCS*
----
bancs -b 10.1.10.205
----

NOTE: `10.1.10.205` is the host to run CARD, `10.1.20.203` is the host to run BANCS.

[source, bash]
.*3. verify setring up*
----
// process on BANCS
~]# ps -ef | grep bancs
root       2176   2146  0 16:55 pts/0    00:00:00 bancs -b 10.1.10.205
root       2177   2176  0 16:55 pts/0    00:00:00 bancs -b 10.1.10.205
root       2178   2176  0 16:55 pts/0    00:00:00 bancs -b 10.1.10.205

// tcp connections on BANCS(BANCS connect to CARD's 8806, CARD connecto BANCS's 8805)
~]# netstat -antulop | grep bancs
tcp        0      0 0.0.0.0:9805            0.0.0.0:*               LISTEN      2177/bancs           off (0.00/0/0)
tcp        0      0 0.0.0.0:8805            0.0.0.0:*               LISTEN      2178/bancs           off (0.00/0/0)
tcp        0      0 10.1.20.203:52400       10.1.10.205:8806        ESTABLISHED 2176/bancs           off (0.00/0/0)
tcp        0      0 10.1.20.203:8805        10.1.20.1:60293         ESTABLISHED 2178/bancs           off (0.00/0/0)

// process on CARD
~]# ps -ef | grep bancs
root       8385   3318  0 16:55 pts/2    00:00:00 bancs -c 10.1.20.203
root       8386   8385  0 16:55 pts/2    00:00:00 bancs -c 10.1.20.203

// tcp connections on CARD
~]# netstat -antulop | grep bancs
tcp        0      0 0.0.0.0:8806            0.0.0.0:*               LISTEN      8386/bancs           off (0.00/0/0)
tcp        0      0 10.1.10.205:8806        10.1.10.1:60292         ESTABLISHED 8386/bancs           off (0.00/0/0)
tcp        0      0 10.1.10.205:39614       10.1.20.203:8805        ESTABLISHED 8385/bancs           off (0.00/0/0)
----

[source, bash]
.*4. Generate Test Data(This will replace default one)*
----
bancs -t -n 10 > /etc/bancs.data
----

[source, bash]
.*5. Test*
----
bancs -e -l 1 10.1.20.203
----

MOTE: Check the message be passed across the ESB, BANCS and CARD.

=== BIG-IP sit between BANCS and CARD

[source, bash]
.*1. BIG-IP Configuration Set up*
----
tmsh create ltm message-routing generic protocol protocol_BANCS_CARD { app-service none disable-parser yes }
tmsh create ltm message-routing generic transport-config tc_BANCS_CARD { profiles add { tcp-bancs { } protocol_BANCS_CARD { } } rules { IRULES_BANCS_TO_CARD } }
tmsh create ltm pool pool_BANCS_TO_CARD members add { 10.1.10.205:8806 { address 10.1.10.205 } } monitor tcp_half_open
tmsh create ltm pool pool_BANCS_FROM_CARD members add { 10.1.20.203:8805 { address 10.1.20.203 } } monitor tcp_half_open
tmsh create ltm message-routing generic peer peer_BANCS_TO_CARD { pool pool_BANCS_TO_CARD transport-config tc_BANCS_CARD }
tmsh create ltm message-routing generic peer peer_BANCS_FROM_CARD { pool pool_BANCS_FROM_CARD transport-config tc_BANCS_CARD }
tmsh create ltm message-routing generic route route_BANCS_TO_CARD { destination-address my_dest peers { peer_BANCS_TO_CARD } }
tmsh create ltm message-routing generic route route_BANCS_FROM_CARD { destination-address my_dest peers { peer_BANCS_FROM_CARD } }
tmsh create ltm message-routing generic router router_BANCS_TO_CARD { app-service none routes add { route_BANCS_TO_CARD } traffic-group traffic-group-1 }
tmsh create ltm message-routing generic router router_BANCS_FROM_CARD { app-service none routes add { route_BANCS_FROM_CARD } traffic-group traffic-group-1 }
tmsh create ltm virtual vs_BANCS_TO_CARD { destination 10.1.10.31:8806 ip-protocol tcp pool pool_BANCS_TO_CARD profiles add { protocol_BANCS_CARD { } router_BANCS_TO_CARD { } tcp-bancs { } } rules { IRULES_BANCS_TO_CARD } source-address-translation { type automap } }
tmsh create ltm virtual vs_BANCS_FROM_CARD { destination 10.1.10.31:8805 ip-protocol tcp pool pool_BANCS_FROM_CARD profiles add { protocol_BANCS_CARD { } router_BANCS_FROM_CARD { } tcp-bancs { } } rules { IRULES_BANCS_FROM_CARD } source-address-translation { type automap } }
----

*2. IRULES_BANCS_TO_CARD*

link:files/IRULES_BANCS_TO_CARD.tcl[IRULES_BANCS_FROM_CARD]

*3. IRULES_BANCS_FROM_CARD*

link:files/IRULES_BANCS_FROM_CARD.tcl[IRULES_BANCS_FROM_CARD]

[source, bash]
.*4. BIG-IP Configuration Clean Up (only used to clean BIG-IP configurations)*
----
tmsh delete ltm virtual vs_BANCS_TO_CARD 
tmsh delete ltm virtual vs_BANCS_FROM_CARD 
tmsh delete ltm message-routing generic router router_BANCS_TO_CARD 
tmsh delete ltm message-routing generic router router_BANCS_FROM_CARD 
tmsh delete ltm message-routing generic route route_BANCS_TO_CARD
tmsh delete ltm message-routing generic route route_BANCS_FROM_CARD
tmsh delete ltm message-routing generic peer peer_BANCS_TO_CARD 
tmsh delete ltm message-routing generic peer peer_BANCS_FROM_CARD 
tmsh delete ltm pool pool_BANCS_TO_CARD 
tmsh delete ltm pool pool_BANCS_FROM_CARD 
tmsh delete ltm message-routing generic transport-config tc_BANCS_CARD 
tmsh delete ltm message-routing generic protocol protocol_BANCS_CARD
----

[source, bash]
.*5. Start Card*
----
bancs -c 10.1.10.31
----

[source, bash]
.*6. Start Bancs*
----
bancs -b 10.1.10.31
----

[source, bash]
.*7. send test message*
----
bancs -e 10.1.20.203
----

[source, bash]
.*8. Check the logs*
----
// BANCS
27-Sep-2022 00:39:35 (1676) BANCS: inbound message from 10.1.20.1:61216, request message to card, message: abcdefghijklmnopqrstuvwxyz
27-Sep-2022 00:39:37 (1675) BANCS: from card: 10.1.20.240:48964
27-Sep-2022 00:39:37 (1675) BANCS: response message from card, message: abcdefghijklmnopqrstuvwxyz

// CARD
27-Sep-2022 00:39:37 (1427) CARD: receive request message from bancs: abcdefghijklmnopqrstuvwxyz
27-Sep-2022 00:39:37 (1427) CARD: response message to bancs, message: abcdefghijklmnopqrstuvwxyz
----

[source, bash]
.*9. Check BIG-IP MRF Rule Log*
----
Sep 26 23:36:13 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <CLIENT_ACCEPTED>: CLIENT_ACCEPTED: 10.1.10.1:61201 - 10.1.10.31:8806
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <CLIENT_DATA>: CLIENT_DATA: 10.1.10.1:61201 - 10.1.10.31:8806
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <CLIENT_DATA>: tcplen: 26, payload: abcdefghijklmnopqrstuvwxyz, bit_data: 0110000101100010011000110110010001100101011001100110011101101000011010010110101001101011011011000110110101101110011011110111000001110001011100100111001101110100011101010111011001110111011110000111100101111010, hex_data: 6162636465666768696a6b6c6d6e6f707172737475767778797a
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <CLIENT_DATA>: data_m: 6162636465666768696a6b6c6d6e6f707172737475767778797a, am: abcdefghijklmnopqrstuvwxyz
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <GENERICMESSAGE_INGRESS>: gm-ingress: len: 26, status: unprocessed, isrequest: 0, seqnum: 0
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <MR_INGRESS>: mr-ingress: len: 26, src: 10.1.10.1:61201, dst: , nexthop: none, route: none, transport: virtual /Common/vs_BANCS_TO_CARD
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <SERVER_CONNECTED>: SERVER_CONNECTED: 10.1.10.205:8806 - 10.1.10.240:61201
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <MR_EGRESS>: mr-engress: len: 26, src: 10.1.10.1:61201, dst: , nexthop: none, route: virtual /Common/vs_BANCS_TO_CARD pool /Common/pool_BANCS_TO_CARD, transport: virtual /Common/vs_BANCS_TO_CARD
Sep 26 23:36:33 test.com info tmm[10629]: Rule /Common/IRULES_BANCS_TO_CARD <GENERICMESSAGE_EGRESS>: gm-egress: len: 26, status: route found, isrequest: 1, seqnum: 0
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <CLIENT_ACCEPTED>: CLIENT_ACCEPTED: 10.1.10.205:48964 - 10.1.10.31:8805
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <CLIENT_DATA>: CLIENT_DATA: 10.1.10.205:48964 - 10.1.10.31:8805
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <CLIENT_DATA>: tcplen: 26, payload: abcdefghijklmnopqrstuvwxyz, bit_data: 0110000101100010011000110110010001100101011001100110011101101000011010010110101001101011011011000110110101101110011011110111000001110001011100100111001101110100011101010111011001110111011110000111100101111010, hex_data: 6162636465666768696a6b6c6d6e6f707172737475767778797a
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <CLIENT_DATA>: data_m: 6162636465666768696a6b6c6d6e6f707172737475767778797a, am: abcdefghijklmnopqrstuvwxyz
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <GENERICMESSAGE_INGRESS>: gm-ingress: len: 26, status: unprocessed, isrequest: 0, seqnum: 0
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <MR_INGRESS>: mr-ingress: len: 26, src: 10.1.10.205:48964, dst: , nexthop: none, route: none, transport: virtual /Common/vs_BANCS_FROM_CARD
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <SERVER_CONNECTED>: SERVER_CONNECTED: 10.1.20.203:8805 - 10.1.20.240:48964
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <MR_EGRESS>: mr-engress: len: 26, src: 10.1.10.205:48964, dst: , nexthop: none, route: virtual /Common/vs_BANCS_FROM_CARD pool /Common/pool_BANCS_FROM_CARD, transport: virtual /Common/vs_BANCS_FROM_CARD
Sep 26 23:36:35 test.com info tmm1[10629]: Rule /Common/IRULES_BANCS_FROM_CARD <GENERICMESSAGE_EGRESS>: gm-egress: len: 26, status: route found, isrequest: 1, seqnum: 0
----
